[[release]] Improve artifacts fetching

diff --git a/.github/scripts/build-cosmo b/.github/scripts/build-cosmo
--- a/.github/scripts/build-cosmo
+++ b/.github/scripts/build-cosmo
@@ -1,6 +1,8 @@
 #!/bin/sh
 set -eux
 
+source configs/default
+
 if [ -z ${GITHUB_ACTIONS+x} ]; then
   # we are not on GA
   if [ $(nproc) -gt 2 ]; then
@@ -13,21 +15,32 @@ else
   numproc=2
 fi
 
+RELEASE_METAS=$(gh release view "${TOOLS_TAG}" --json assets --jq '.assets')
+METAS=""
+for name in llvm.zip aarch64-gcc.zip x86_64-gcc.zip; do
+  API_URL=$(echo "${RELEASE_METAS}" | jq -r ".[] | select(.name == \"${name}\") | .apiUrl")
+  if [ -z "${API_URL}" ]; then
+    echo "Cannot find asset ${name} in release ${TOOLS_TAG}"
+    exit 1
+  fi
+  META=$(gh api "${API_URL}" --jq '{name, digest: (.digest | sub("^sha256:"; "")), url: .browser_download_url}')
+  METAS=$(printf '%s\n%s' "${METAS}" "${META}")
+done
+
+METAS=$(jq -s '.' <(printf "${METAS}"))
+
 cd superconfigure/cosmopolitan
 
 python3 - >tool/cosmocc/package.sh.tmp <<EOF
 import re
-hashes = {
-  'aarch64-gcc.zip': '580076b885b469a0e819dc6ee37aa2dfae3ec1db7d864c406ad813fc4297996c',
-  'x86_64-gcc.zip': 'cdc54e48a521aabd8488ebfc66aba000f556ed70c6918f194a825e770e8bf3eb',
-  'llvm.zip': '7dfa4007c9caf65e3f4871beddd5c730f0e1deb13a43050318c6dfdf20fa44ce',
-}
+
+files = ${METAS}
 import re
 with open('tool/cosmocc/package.sh', 'r') as f:
   content = f.read()
-for filename, sha256 in hashes.items():
-  pattern = re.compile(r'fetch.*?{}.*?&'.format(filename))
-  replacement = f'fetch https://github.com/hsfzxjy/cosmocc-repack/releases/download/4.0.2-28-ge7e5856b8/{filename} {sha256} &'
+for f in files:
+  pattern = re.compile(r'fetch.*?{}.*?&'.format(f['name']))
+  replacement = f'fetch {f["url"]} {f["digest"]} &'
   content = pattern.sub(replacement, content)
 print(content)
 EOF
